### ISSUE TITLE
转换pdf时报错

### ISSUE THREAD

**Issue by wstray** [chatdoc-com/OCRFlux#8]
2025-07-03 18:48:11,772 - __main__ - ERROR - Exception in process_pdf for 73_20240207.pdf: unhandled errors in a TaskGroup (1 sub-exception)
  + Exception Group Traceback (most recent call last):
  |   File "/root/OCRFlux/ocrflux/pipeline.py", line 415, in process_pdf
  |     async with asyncio.TaskGroup() as tg:
  |   File "/root/miniconda3/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/root/OCRFlux/ocrflux/pipeline.py", line 436, in process_pdf
    |     results = [task.result() for task in tasks]
    |                ^^^^^^^^^^^^^
    | asyncio.exceptions.InvalidStateError: Result is not set.
    +------------------------------------

**Comment by tangyu2001** [comment]
We have fixed the bug in our updated code.

**Comment by baiwenhao617-rgb** [comment]
I have used the latest pipeline.py, but the error still persists
